# General
name: Hyeonjae Blog
description: "Hyeonjae's blog"
url: http://hyeonjae.github.io

markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: hyeonjae
twitter: 
github: hyeonjae
google: 

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
