title: "Nowpark"
author: "Hyeonjae"
description: "A Blog by jekyll"
#subheading: "Really cool blog about ... something"
more: "read more"
url: "http://hyeonjae.github.io"
#baseurl: "/" # comment out if in root directory

comments:
    disqus: "hyeonjae"
#    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

gems:
  - jekyll-sitemap

links:
  - github: "https://github.com/hyeonjae/"

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
